### ISSUE TITLE
New implementation of Streama has no settings page

### ISSUE THREAD

**Issue by dln949** [streamaserver/streama#1019]
Ubuntu 18.04.5, Streama 1.92

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

I start streama on the server computer using the command   java -jar streama-1.9.2.jar

I end up with this comment in the terminal, with no error messages:  
"Grails application running at http://localhost:8080 in environment: production"  

When, on the remote computer, I navigate to http://xxx.xxx.x.x:8080 in a web browser, and login with admin and admin, on the server machine in the terminal I see this message:  "ERROR grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter - An internal error occurred while trying to authenticate the user.
org.springframework.security.authentication.InternalAuthenticationServiceException: localhost:389; nested exception is javax.naming.CommunicationException: localhost:389 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]"  

Questions:  

1)  Is some kind of GUI window supposed to start up?  I don't see one.  But, I don't know if there is supposed to be one.  

2)  On a remote computer, using a web browser, I navigate to http:  xxx.xxx.x.x:8080.  I get a streama screen.  But, there is no settings page.  Where do I find the settings for streama?  

3)  Streama wants to use port 8080.  But, I already have another application using that port.  How do I change the port that streama uses?  

4)  What does that grails error message mean?  I am not a tech person, I have no idea what grails is.  

Thanks for any help.

**Comment by mach327** [comment]
1. No, no gui window. It's a web service, so all interaction is from a web interface. Servers are almost always configured and run entirely from the command line and left to run automatically, which GUIs are not well suited for.

2. You should be shown the settings page when you start Streama for the very first time. If you've configured it already, log in to Streama as an admin user and look for the "Admin" button in the top right. But, you may not be getting this far because of the error in question 4.

3. The port is configured using [application.yml](https://github.com/streamaserver/streama/blob/master/docs/sample_application.yml), directions are in the linked file.

4. I'm not as familiar with Streama as one could be, just another random Streama user, but that grails error looks like it's trying to connect to an LDAP authentication backend, which you don't have running. I'm not sure why it would be trying that, unless you configured it to do so. Grails is the web framework used to build Streama. A web framework is a piece of code that makes it easier to write new web applications. 

I'm afraid I probably can't help you much further, but figured I'd help however much I could. Best of luck!

**Comment by dln949** [comment]
Thanks, your link to the application.yml helped, I was successfully able to change the port to 8085 and avoid a conflict on 8080 with another application.  

However, still getting the grails error, still not able to see the settings button.  Something's very wrong.....

**Comment by mach327** [comment]
Grails error: Yeah, that sounds odd.
You might try it as a brand new installation so it creates a new database and such from scratch and see if that goes better?

**Comment by dln949** [comment]
Yep, brand new installation did the trick, thank you.
