### ISSUE TITLE
https + wrong user or password = error

### ISSUE THREAD

**Issue by vaguiners** [streamaserver/streama#392]
When using https in the base URL and the user misses the login or password, the user is redirected to  https://domain:80/login/auth?login_error=1 that causes an error in Cloudflare because https does not use port 80, but 443

I tried to use https://domain:443/ on baseurl and still redirect to https://domain:80

**Comment by PiperMp3** [comment]
With SSL and especially Cloudflare, you have several options of SSL, you can have that Half-baked option whereas the connection between User and Couldflare is SSL, but Cloudflare and your Streama is not. However it appears as SSL to the naked eye for what they are concerned.  (Easy)
The other option, SSL everywhere - may be somewhat of below here..

Now, SSL with Streama, I suppose you are looking at a way of piping Streama's traffic to 443 instead of 80, or 8080 as it uses by default.
Your Streama may basically think "I'm port 80!" while your Cloudflare thinks it's 443.

Haven't seen any way to change the port Streama would bind to - so if you managed to get yours from 8080 to 80 - I would also like to know how - The other way is to rebuild Streama from source and change it in the code I would imagine.

Not exactly sure how dularion pictured Streama under SSL, and it may be that it's not designed for it (yet).
So dularions input on this matter would be cool indeed.

**Comment by dularion** [comment]
Hi guys, 
Well if I'm mentioned by name there is no way I'm not responding :) 
Actually there is a way to run streama via ssl, but streama alone isn't quite capable. You use cloudflare for SSL? I guess that could work, but remember, then all traffic goes through cloud flare.. And we're talking videos here ... Not sure if you really want that. But anyway, in that case I guess all you need to do is change your port, and for that please check here:  https://github.com/dularion/streama/wiki/Getting-started#8-how-do-i-change-the-port

Alternatively, you could do it like me and hook an nginx or Apache in front that handles SSL and routes the requests. If you need more instructions let me know

**Comment by PiperMp3** [comment]
Yea actually those instructions would be sweet.
You using self certificate or letsencrypt or so?

But yes, instructions for nginx or Apache in front would be swell!

**Comment by vaguiners** [comment]
I think there is a way to simplify this problem.

If you run the streama on port 8080 or on any port other than 80, even without SSL, the stream will redirect to port 80 and will reproduce the error.

**Comment by CardealRusso** [comment]
This still happens, but not only when users misses the credentials, on sucessufly login it redirects to https::/domain:80
