### ISSUE TITLE
Question about remote access

### ISSUE THREAD

**Issue by haze135** [streamaserver/streama#483]
Hello, i set up Streama but i have a question.. How can i access Streama when i'm not at home?

**Comment by jacobdu215** [comment]
This isnt an issue with the software. Most home routers have firewalls so no one can really access your system remotely. Now to get around this, you would need to port forward the ports related to streama, which is 8080 and if you switched to ports 80 and 443 for SSL and HTTP, you would port forward those. Just google how to port forward NAMEOFROUTER on google and it should come up with what you need. If it doesnt have your model its always similar. Then to access it, you would go to your external IP from outside your network. When you do, however, you need to change the access location in the streama settings. Once you do so, you do need to access from your external IP at all times even when under the same network. Hope this helps.

**Comment by haze135** [comment]
Thank you  for the reply. I need a public ip right?
Sorry i'm a newbie.

**Comment by shaynethiessen** [comment]
Yes, you can find out what your public ip by going to https://www.whatismyip.com/
If you have a basic home internet plan, your public ip might not be static, so it will change occasionally.

**Comment by jacobdu215** [comment]
Yes or just google "IP" or "what is my IP"

**Comment by Shrinks99** [comment]
You can set up a DDNS service and use [one of the many free domans ](https://freedns.afraid.org) on that site so that your server IP is constantly accessible from outside of your LAN.  Alternatively buy a cheap domain and do the same thing.

**Comment by rowbawts** [comment]
I have a fully functioning Streama setup remote and locally problem is I can't have a local and remote base url at the same time obviously so how can I resolve that so I can use it remotely and locally.

**Comment by Shrinks99** [comment]
You can't.  I believe this will be amended in Streama 1.3 but you're stuck choosing one or the other until then.

**Comment by jacobdu215** [comment]
rowbawts, cant you just use your external IP while on your local network? It shouldnt affect performance really.

**Comment by rowbawts** [comment]
jacobdu215, I tried that for some reason I can't connect using the external IP from within my LAN.

**Comment by Jeronimo95** [comment]
Your router may not support (or not be configured for) hairpin NAT.

**Comment by shaynethiessen** [comment]
@rowbawts I have that same problem here with my cheap ISP provided router. Sadly there is nothing that can be down about that unless you get a new router.

It would be great if Streama didn't require entering a base URL and instead automatically figured out the URL that was being used to access Streama.

**Comment by Jeronimo95** [comment]
@shaynethiessen Removing the base URL requirement is something we want to do in the near future.

**Comment by sphynxkitten** [comment]
Not sure if this was solved, but this is possible by setting a static ip, then port forwarding the necessary ports, I'll share some instructions for Windows users (I'm on Windows 10), but they wont be comprehensive, Google will be better because of different modem types, ISPs etc..

###**Making a static IP: (not sure if isp have restrictions on this)**
**1:** Connect to the network you'll constantly be connected to.
**2:** Open a command prompt, type: netsh interface ip show config - leave it opened to the side.
**3:** Click the wifi icon in the icons tray, and click "Network and Internet settings".
**4:** Under "Change your network settings", click "Change adaptor options".
**5:** If you're using Ethernet, click Ethernet, otherwise if you're using wifi, click wifi.
**6:** Click "Properties" & grant permissions if you need to.
**7:** Double click "Internet Protocol Version 4 (TCP/IPv4)
**8:** Click "Use the following IP address" and enter the details (refer back to the command prompt)
**IP address**; the IP address under "Configuration for interface "wifi"" (as you're newly doing this, use the one that's displayed, as you're using it right now) (for an example later on: lets use 192.168.1.10)
**Subnet mask**: It should automatically fill out the address. If not, it's under IP address as Subnet Prefix, but use the mask address, on the end in brackets.
**Default Gateway**: This is your modem address, usually the same as IP address, but with a 0 or 1 at the end, double check with the command prompt.
**9:** Click "Use the following DNS server addresses" and enter the details (also refer to command prompt)
**Preferred DNS server**: Use the first IP address next to "Statically configured DNS server".
**Alternate DNS server**: If you have 2 address under "Statically configured DNS server" then use the second one. If not, this doesn't matter.
**10:** Click "Validate upon exit" and click "Ok" and make sure you've still got internet. If so, perfect, if not, check your settings and make sure they're correct, number by number.

###**Portforwarding:**
First of all, this will be different for all modems, so it's best to Google it.

**1:** You need to access your modems interface, by visiting the default gateway IP, username is usually admin, password is usually admin or password. Find your portforwarding settings and go to them.
**2:** Where it asks for your IP address, use the one you set for your IPv4, in this example, it would be 192.168.1.10.
**3:** The port you'd want to forward would be 8080, though if you've changed the defaults, you'll know what to forward.

You'll then probably have to reboot your modem for the ports to be open, you can check them at canyouseeme.org
Then you can access our site from either localhost:8080 or for example, 111.111.11.111:8080 (your IP:8080).

If you want to access it from just localhost or 111.111.11.111 (your IP), you need to set the port to 80, and forward that port.

**Comment by Guima001** [comment]
@sphynxkitte

I was able to complete the whole process until I released the external IP and access via 8080, an excellent explanation!

But I can not say the same about a targeting of port 80, could you guide me to segment this port externally? Even though the intern stays on the 8080, I already researched this, but I did not get the success I was hoping for.

**Comment by Jeronimo95** [comment]
If your router supports it, you might be about to set port 80 externally forwards to port 8080 internally.

Alternately you could [setup nginx](https://github.com/dularion/streama/wiki/Nginx-as-a-reverse-proxy) to proxy port 80 and have your router just forward port 80.

Some ISPs will block port 80 though,
