### ISSUE TITLE
Dont show File location by json response

### ISSUE THREAD

**Issue by siteripper** [streamaserver/streama#591]
### Issue description
The json response object gives the exact filename and path to everyone. For privacy issues it would be better to be removed.

**Comment by dularion** [comment]
You are right. here are a few examples: 

### Local Video File
![image](https://user-images.githubusercontent.com/936076/38387751-26851a8a-3919-11e8-92f6-0d155505b710.png)

### Direct upload (not the entire path, but the sha)
![image](https://user-images.githubusercontent.com/936076/38387796-5afe9386-3919-11e8-9e9d-e87386ffba03.png)

### External link (is actually required, but is very redundant) 
![image](https://user-images.githubusercontent.com/936076/38387835-8ba5b424-3919-11e8-9829-b4b025222fcb.png)



So if I am not mistaken (correct me if I am) then the issue is really only for local files, right?

**Comment by Jeronimo95** [comment]
This is mainly about the `localFile` having the full path streama uses, this is probably only needed to be sent for content manager pages. 
But also, it does seem the player gets a lot of info it doesn't use, maybe we could trim the fat so requests only get the info that they *need*.

**Comment by dularion** [comment]
So ive drastrically reduced the data returned by the JSON now. this can potentially break the player in some cases, so pls guys help me test this before we add it to the next stable release. You can test it here https://github.com/streamaserver/streama/releases/tag/v1.6.0-RC4

**Comment by siteripper** [comment]
Looks great. Nevertheless it would be great when IMDB-ID and TMDB-ID are still returned by the JSON. This is very usefull for implementing in Kodi-Addons or exact scraping there.
