### ISSUE TITLE
Feature Request: WebDAV integration

### ISSUE THREAD

**Issue by sunjam** [streamaserver/streama#619]
This feature request is for mounting remote folders to Streama via **WebDAV** protocol as though they were local folders.

**Why?**
- Simple protocol that is understand by all modern desktop computers, [is built-in to Kodi](https://kodi.wiki/view/WebDAV), and [Nextcloud](https://github.com/streamaserver/streama/issues/553), Seafile, Pydio, Owncloud, etc.

**Comment by dularion** [comment]
sounds kinda cool, but the current way to do it is to mount your external drive using your OS and then let streama access it as though it really was a local drive. Or is there a disadvantage to that approach compared to WebDAV?

**Comment by sunjam** [comment]
Hi, the advantage is you can easily mount remote storage and sync files via Webdav, no local files needed.  It is a universal, open protocol that would allow you to add remote storage support to streama.

**Comment by Jeronimo95** [comment]
This. We don't really want to be maintaining extra code to mount storage when there are already existing solutions (eg fuse) that are far more robust.

**Comment by idnfs-storage1** [comment]
Hi, I would like to reopen this enhancement request.
The use case being that some of us will run the server on docker. Most of the time especially with free service that offer to run docker, we can't mount webdav to our server as the /dev/fuse is not accessible. If you think managing the mount is too much to do from within the current code, please consider adding support for http/https URL as a source instead of local file. In case the webdav server the user is having need to be authenticated, we can use rclone to serve the webdav as http or as another locally running webdav. This way we don't need the /dev/fuse.
Thanks
