### ISSUE TITLE
Add an option to hash the login email

### ISSUE THREAD

**Issue by rhulha** [streamaserver/streama#634]
Inspiration:  https://blog.code.org/post/147756946588/codeorgs-new-login-approach-to-student-privacy

**Comment by Jeronimo95** [comment]
I don't think this is a good idea for streama, as mention in the article "This was not an easy trade-off, because every Web site values the ability to contact their “customers.”" We use the emails for invites, so it would be fairly pointless to hash those.
You don't even need to enter an email for creating a user manually.
