### ISSUE TITLE
Streama App Setup Page

### ISSUE THREAD

**Issue by rajohn007** [streamaserver/streama#727]
How to get rid of setup page in Streama App and directly load to my host site. Having a setup page where user have to put host websites address manually is annoying.

**Comment by dularion** [comment]
we cant do that unfortunately, because each and ever one of you have different hosts, one might be called "myvideos.org" another maybe "stream-videos.io". so when the app comes from the play store it is kept "generic", i.e. nothing like that is prefilled and your users have to use your specific url.
