### ISSUE TITLE
needs more types of database

### ISSUE THREAD

**Issue by CardealRusso** [streamaserver/streama#749]
mysql is slow, heavy and outdated,  not usable nowdays
and h2 is just for testing

**Comment by kerberjg** [comment]
PostgreSQL is an excellent alternative, and requires almost no modification on the server.

Alternatively, you can use MariaDB as a drop-in replacement for MySQL, it provides full compatibility. I think most of us Streama users actually run Streama on MariaDB

**Comment by DerVerruckteFuchs** [comment]
The database table naming convention needs to be tweaked a bit to get PostgreSQL working. Namely the `user` table is a reserved keyword for PostgreSQL, which is issue #409. I have a migration script I've submitted for a pull request if anyone is interested in looking at in pull request #647. You'll need to uncomment the lines in the `build.gradle` related to the PostgreSQL driver before building so that Streama can interact with a PostgreSQL database.
