### ISSUE TITLE
ok what is going on?

### ISSUE THREAD

**Issue by CardealRusso** [streamaserver/streama#753]
14 days without updates already
is this project dead?

**Comment by dularion** [comment]
Oh man, you have high expectations, huh? I get it, you found this software and you like it and you want the contributors and everyone to be super active.
Unfortunately, we don't have so many contributors in the project and all of us have private lives, work etc... Keep in mind, nobody is paying us for our work on streama.
I do wanna contribute more, but sometimes it just doesn't work out... 

But let's hope we get more contributors for the future!

**Comment by kerberjg** [comment]
@CardealRusso other than being disrespectful towards passionate developers who dedicate the free time they have available to this project, your behavior is:

- not constructive
- doesn't help the project in any way/shape/form
- is in violation of the Github Community Guidelines
- is in violation of the Streama community rules

As a concerned member of this community I'm asking you to respectfully close this issue and cease such behavior.

Otherwise I will ask a project member to close this issue, and I will take it upon myself to file a community guideline violation claim to GitHub regarding your profile.

I hope this has been constructive enough

**Comment by mcrook250** [comment]
> Oh man, you have high expectations, huh? I get it, you found this software and you like it and you want the contributors and everyone to be super active.
> Unfortunately, we don't have so many contributors in the project and all of us have private lives, work etc... Keep in mind, nobody is paying us for our work on streama.
> I do wanna contribute more, but sometimes it just doesn't work out...
> But let's hope we get more contributors for the future!

I'm sorry this is one of the reasons I don't contribute anymore. The last project I was a part of was websitepanel and that started to be a pain because of people like that. Im not rich, but ill paypal you for your time if you can fix the few things I listed on my ticket from before. I think you should just give up using the default player on android and improve on your html5 one and load that instead. Support for real buffering is a must. Anyways, people have families to feed and a life and doing this as a hobby should be rewarded from time to time.

Matt

**Comment by dularion** [comment]
Guys, ill close this issue for now. but if anyone wants to add something we can pick it back up later
