### ISSUE TITLE
[Bug/Feuture] Subtitles

### ISSUE THREAD

**Issue by Ircas** [streamaserver/streama#813]
I just found out that the subtitles button (on RC 11 version) is always visible inside the player even if I have not added a subtitles on my video. 

Maybe this was added or broke when @dularion added add bulk subtitles feuture? 

Some users (including myself) may never use subtitles on streama so there should be one of the following options available. 

A) Only show the subtitle button/option inside the player if a subtitle is actually preset.

Or

B) Have an option in admin area (check box) just like the allow users to download option to disable subtitles thus the button alltogether.

**Comment by Norwelian** [comment]
I think it's something intentional, as the subtitle menu now serves the purpose of subtitle track selection, video track selection and (in the future I think) audio track selection. That, plus the subtitle size feature when it's working.
In the case of the video not having subtitles, it says "No subtitle" in the subtitle track selection zone, correctly, so maybe it's a better idea to have the B option, in case you don't want the full menu available.
(Obviously, this is just my opinion as per usual XP)

**Comment by dularion** [comment]
Yep, like @Norwelian says, this has to do with the video track selection. But it makes sense to hide the button if neither multi-subtitle nor multi-video-track is available for the video. If either is available, I'd show the button again. That would be easiest and most intuitive I believe. Or what do you guys think?

**Comment by dularion** [comment]
Will be fixed in 1.7.0 stable
