### ISSUE TITLE
Bug or bad setup, I don't know.

### ISSUE THREAD

**Issue by runawaydevil** [streamaserver/streama#824]
Hi guys,

I would like to ask one:

1 - In Manage Content -> File Manager. When I try to delete some movie from database I get the message: An error an error occurred [Object object], someone knows what's going on? And this kind of deleting remove the movie from the database or erase from my HDD?
I would like to know if someone has a solution for this. I created the entire system using the root, but I set all permissions for my personal user too. Anyway, not working. If there is a way to start the movie database again, please, let me know :)

**Comment by dularion** [comment]
You are asking multiple questions at once. 
to address each one: 
> In Manage Content -> File Manager. When I try to delete some movie from database I get the message: An error an error occurred [Object object], someone knows what's going on?

This is simply a bug and should definitely be addressed 

> And this kind of deleting remove the movie from the database or erase from my HDD?

This behaves differently for uploaded files vs files from the localFiles directory. Actually, this has not been tested thoroughly since localFiles was added so I am not sure the feature still works at all 

> I created the entire system using the root, but I set all permissions for my personal user too. Anyway, not working.

Not sure what you mean by this 

> If there is a way to start the movie database again, please, let me know

What database?

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic, I am closing it if this is not solved please reopen the issue.
