### ISSUE TITLE
[BUG] 429 http error for genre at start service

### ISSUE THREAD

**Issue by sofianemkdm** [streamaserver/streama#832]
### Issue description

When launching the streama service, the following errors appear:

 WARN grails.app.services.streama.TheMovieDbService - could not load genres this time, Server returned HTTP response code: 429 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key={API_KEI}f&language=fr

WARN grails.app.services.streama.TheMovieDbService - could not load genres this time, Server returned HTTP response code: 429 for URL:  https://api.themoviedb.org/3/genre/tv/list?api_key={API_KEI}f&language=fr

therefore impossible to run the app

### Steps to Reproduce

1. Ready to use version and configure with MySQL
2. Add some tv shows and movies (maybe the tv shows that I added manually poses problem)
3. Restart the service
4. Errors appears

### Additional Info

The application was running very well until the moment to restart the service. I tried to use v 1.6: same problem.
I can send you a clean dump of users if you can not reproduce the problem.
J'ai passé beaucoup d'heure dans les ajout manuel. :(

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Streama version**: 1.7.0
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**:
configured with mysql
run as a service (i follow your wiki)
I just change default sort in template.

**Comment by sofianemkdm** [comment]
J'ai passé beaucoup d'heure dans les ajout manuel. :( => I spent a lot of time in manual adding. :(

**Comment by dularion** [comment]
See here for reference: https://www.themoviedb.org/documentation/api/status-codes?language=sk-SK

429 means "Your request count (#) is over the allowed limit of (40)."

During startup, the application adds all missing genre. If you reach the limit during startup, just restart a few times until all genre were added. Thats a way to "trick" it. 
Also, seems like this is related to https://github.com/streamaserver/streama/issues/830, because usually genre should be added directly when creating the movies/shows, not during startup. The startup thing is really just a fix for any genre that slip through the cracks, but it should usually not be necessary.

**Comment by sofianemkdm** [comment]
Perfect, I read the other issue in the meantime, and the service is running correctly now.
Thank you very much for your response and speed.
