### ISSUE TITLE
[Issue] File / Movie title matching

### ISSUE THREAD

**Issue by alxbrn** [streamaserver/streama#841]
This might have been asked before, but I thought I would just ask since I couldn't find the exact question I wanted to ask.

I was attempting to do a test to see what type of movies it would find when changing file names to stupid stuff and normal stuff.

Let's take a movie like "12 Years a Slave" as a example, if the name of the movie is the exact name as the title it wont find anything, also when you replace the spaces with "." as discussed in previous issues it still doesn't find any matches. But as soon as you add a 4 figure number to the title for example : "12.Years.a.Slave.0000" it finds the correct result.

images of matching:
[with random numbers](https://i.gyazo.com/2dd87ab441ecb0ce4b3c1354cb9c31aa.png)

[without random numbers](https://i.gyazo.com/fb649f15043ec4645bf1e6eb167329f7.png)

Why does this happen? Shouldn't it just be able to find a match without the release date / year inside the file name.

(The title to TMDB name matching is horrible and... Consider if you have a collection of +1000 movies / tv shows, would you now have to redo your whole file / directory naming structure? In theory you shouldn't even need all of this regex stuff as TMDB already has a Similarity algorithm in place to find the best match for your search result (only if your file is decently named such as: "12 years a slave" or "12 YeaRs A SlavE" etc...) )

I know you can easily change the matcher yourself, but wouldn't it be simpler just to improve the regex parameters?

**Comment by Ircas** [comment]
I agree with this one search should be more slack and not so exact. 

Also I have discovered that sometimes when a movie title is similar to an older movie or a diffrent one it imports the wrong data.

Of course you can manually add the movie and then insert the video file but that goes against bulk adding files. I have a collection of over 10.000 movies and over 350 tv shows just imagine the time I have to spend to manually add or edit each data.

The way it should work in my opinion is as follows. 

Use bulk insert to add the data. When a movie or show doesnt get a 100% match it should have a dropdown to select the one you want. This way even if there are alot of wrong result it would be much easier and faster to correctly bulk insert your videos.

Streama has the pontential to be the best library platform out there. Better than plex better than kodi even better that netflix. 

Of course there is also the issue about making a free open source project like streama. Some devs have worked really hard without getting paid for something beutifull. Then some "nice" guy comes along takes the open source and makes it into a money making machine.

Netflix will decline by the end of the year due to other companies making their own streaming platform. Disney+  and HBO are already on the works.

So for a user is like 15 dollars for netflix 10 dollars for Disney 10 for HBO 10 for hulu thats like 45 a month. 

Imagine a pirate site having all the above asking for a 10 dollars fee. This will bring attention to streama. Maybe even legal attention (look into kodi  addons that are just scrapppers)

My idea is make streama a fremium model. Give out the code for free but if you want extra things and support pay for it. Devs make money the project gets updated and we are all happy with it. 

Streama already is getting better and people love it. Just look the state it was when it started or even a couple months ago.

Sorry for long post and highjaking the first post but I would like your opinion on this...

**Comment by dularion** [comment]
the four-digit number is relatively new and is intended for a four-digit year. With that, multiple matches can be dealt with, like aladdin.2019 and aladdin.1994. 
I also like @Ircas idea to add a dropdown. sometimes tmdb finds really stupid stuff though, so it might get annoying. but worth a try! 

Regarding the rest if your post: thanks for your praise and your acknowledgement of the issues we are facing, but i am optimistic that with more devs or your ppls patience, we can create something great :)

**Comment by alxbrn** [comment]
If you want to support year search (which i agree with is great, on the condition that it's implemented correctly), why not just make it optional and not required? AKA check if it contains a 4 digit number with your current method (regex matching) then look up with year otherwise don't look up with year.
