### ISSUE TITLE
[Features Request] Streamline New User Experience?

### ISSUE THREAD

**Issue by MrArca9** [streamaserver/streama#894]
Hello gents, feel free to close this since it's more of a feedback / feature post and not necessarily an issue. Here's some things I think could streamline the experience for new users:

1) Set jar file as an executable? I am not sure if this is possible do to the development environment. Maybe make the main class check permissions of current directory to ensure read/write on boot, possibly force open a CMD window for output. Or have log file in same directory. This will solve issues with new users not understanding how environment variables work. 

2) If one doesn't exist, the Jar file should also generate a default application.yml.  If a new update is released, and a user did not read the release notes, they can .bak their old yml, and run the jar for a new one to force a new one to generate that will work.  Additionally I am sure many users, myself included, simple copy and paste the default yml. 

Thanks for all the work!

**Comment by sysosmaster** [comment]
Regarding point 1. This is not transparently possible (its due to how java actually works). 
 what could work is a Shell & batch script to actually start the application.

Regarding point 2. the yaml file should be created if not existing. if there is a conflict or missing config the app should either autofix it or abort starting up with a message.
