### ISSUE TITLE
Streama having errors while trying to fetch trailers

### ISSUE THREAD

**Issue by peterpt** [streamaserver/streama#899]
Sometimes this problem appears , but if i try it other time then it may not appear .
I have no idea if this is related to the queries to themoviedb.org

Streama Version : 1.7.2
OS : Linux

the log report :
Configuring Spring Security Core ...
... finished configuring Spring Security Core

ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for null
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for null
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 10428
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 27576
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 405774
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 206487
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 180
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 245703
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 782
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 1946
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 515741
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 520901
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 47931
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 28355
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for 405775
ERROR grails.app.services.streama.TheMovieDbService - problem during getTrailerForMovie for null
INFO streama.Application - Started Application in 141.853 seconds (JVM running for 154.644)

**Comment by drexlma** [comment]
firewall block the connection to TheMovieDbService?

**Comment by sofianemkdm** [comment]
https://github.com/streamaserver/streama/issues/832

**Comment by LukeSteward** [comment]
#832 

Dularion said
See here for reference: https://www.themoviedb.org/documentation/api/status-codes?language=sk-SK

429 means "Your request count (#) is over the allowed limit of (40)."

During startup, the application adds all missing genre. If you reach the limit during startup, just restart a few times until all genre were added. Thats a way to "trick" it.
Also, seems like this is related to #830, because usually genre should be added directly when creating the movies/shows, not during startup. The startup thing is really just a fix for any genre that slip through the cracks, but it should usually not be necessary.

I suspect that this is the same issue
